// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBPqcaz4-rchqroAg1KyerLbU3fM5tUwqY',
    appId: '1:335986082637:web:7284b1ffb7a721b1a72d04',
    messagingSenderId: '335986082637',
    projectId: 'whatsapp-e462b',
    authDomain: 'whatsapp-e462b.firebaseapp.com',
    storageBucket: 'whatsapp-e462b.firebasestorage.app',
    measurementId: 'G-RTGCXSXQTL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBu0Ps_nXqK5OzvxLXbZrvQkFm_Zat5kg8',
    appId: '1:335986082637:android:58c96a469e908b2aa72d04',
    messagingSenderId: '335986082637',
    projectId: 'whatsapp-e462b',
    storageBucket: 'whatsapp-e462b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDJKofpm1W4kdFN-p-PLSZpVSrecr5t4pY',
    appId: '1:335986082637:ios:bd9783c077216aeba72d04',
    messagingSenderId: '335986082637',
    projectId: 'whatsapp-e462b',
    storageBucket: 'whatsapp-e462b.firebasestorage.app',
    iosBundleId: 'com.example.flutterChatAppPlayable',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDJKofpm1W4kdFN-p-PLSZpVSrecr5t4pY',
    appId: '1:335986082637:ios:bd9783c077216aeba72d04',
    messagingSenderId: '335986082637',
    projectId: 'whatsapp-e462b',
    storageBucket: 'whatsapp-e462b.firebasestorage.app',
    iosBundleId: 'com.example.flutterChatAppPlayable',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBPqcaz4-rchqroAg1KyerLbU3fM5tUwqY',
    appId: '1:335986082637:web:ad655f11deb4bdf5a72d04',
    messagingSenderId: '335986082637',
    projectId: 'whatsapp-e462b',
    authDomain: 'whatsapp-e462b.firebaseapp.com',
    storageBucket: 'whatsapp-e462b.firebasestorage.app',
    measurementId: 'G-Z20Z0C4EN0',
  );
}
